name: Scrape LDSH Announcements

on:
  schedule:
    - cron: '0 * * * *'  # 每小時執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium
    
    - name: Run scraper
      run: python scraper.py
      
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    
    - name: Commit and push if changes
      run: |
        git add ldsh_announcements.rss
        timestamp=$(date -u)
        git commit -m "Update RSS feed: ${timestamp}" || exit 0
        git push